version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped

  # Pre-pull language images to improve first-run performance
  python:
    image: python:3.9-slim
    command: /bin/true
    deploy:
      mode: global
      restart_policy:
        condition: none

  node:
    image: node:16-slim
    command: /bin/true
    deploy:
      mode: global
      restart_policy:
        condition: none

  java:
    image: openjdk:11-slim
    command: /bin/true
    deploy:
      mode: global
      restart_policy:
        condition: none

  cpp:
    image: gcc:latest
    command: /bin/true
    deploy:
      mode: global
      restart_policy:
        condition: none 